package org.yearup.data.mysql;

import org.springframework.stereotype.Component;
import org.yearup.data.OrderDao;
import org.yearup.models.Order;

import javax.sql.DataSource;
import java.sql.*;

@Component
public class MySqlOrderDao extends MySqlDaoBase implements OrderDao {

    // pass datasource up to base dao so we can open db connections
    public MySqlOrderDao(DataSource dataSource) {
        super(dataSource);
    }

    @Override
    public Order create(Order order) {

        // insert a new order row tied to a user
        // order_id is auto-generated by the database
        String sql = """
                INSERT INTO orders (user_id)
                VALUES (?)
                """;

        // try with resources ensures connection statement are closed properly
        try (Connection connection = getConnection(); PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            // bind the user id to the insert
            statement.setInt(1, order.getUserId());

            // execute insert
            statement.executeUpdate();

            // grab the auto generated order_id from the db
            ResultSet keys = statement.getGeneratedKeys();
            if (keys.next()) {
                // attach generated id back onto the order object
                order.setOrderId(keys.getInt(1));
            }

            // return the order with its new id populated
            return order;
        } catch (SQLException e) {
            // bubble up db errors
            throw new RuntimeException(e);
        }
    }
}